name: custom pipeline
on:
 workflow_dispatch: 
 push:
  branches:
    - master
    
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - name: checkout code
    uses: actions/checkout@v4

  - name: setup-python
    uses: actions/setup-python@v5
    with:
      python-version: 3.15

  - name: verify
    run: |
      python --version
      pip --version
   
